### ISSUE TITLE
libdescale.dll cannot be used as a plugin for AviSynth.

### ISSUE THREAD

**Issue by DonCanjas** [Jaded-Encoding-Thaumaturgy/vapoursynth-descale#4]
> Includes a VapourSynth and AviSynth+ plugin

![imagem](https://github.com/Jaded-Encoding-Thaumaturgy/vapoursynth-descale/assets/80267631/c4155385-9b89-4191-aea9-62497e9b3429)

```c++
LoadPlugin("C:\Users\jonas\Desktop\libdescale.dll")
```
![imagem](https://github.com/Jaded-Encoding-Thaumaturgy/vapoursynth-descale/assets/80267631/523c09d1-652e-4e8a-ad60-430b2268f797)

**Comment by arch1t3cht** [comment]
The readme was outdated there, this fork effectively has no AviSynth support unless someone PRs it. You'll have to use [upstream](https://github.com/Irrational-Encoding-Wizardry/descale).
